### ISSUE TITLE
Angular 11 compile error at 3.0.0-alpha.0

### ISSUE THREAD

**Issue by osmanraifgunes** [eclipsesource/jsonforms-angular-seed#42]
Error: ./node_modules/@jsonforms/angular-material/__ivy_ngcc__/lib/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/app/node_modules/@jsonforms/angular-material/__ivy_ngcc__/lib/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Storage.provideSync (/app/node_modules/@angular-devkit/build-angular/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync (/app/node_modules/@angular-devkit/build-angular/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:289:32)
    at Object.read (/app/node_modules/@ngtools/webpack/src/webpack-input-host.js:25:42)
    at /app/node_modules/@angular-devkit/core/src/virtual-fs/host/create.js:24:45
    at Observable._subscribe (/app/node_modules/@angular-devkit/core/src/virtual-fs/host/create.js:14:25)
    at Observable._trySubscribe (/app/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/app/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/app/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:25:20)
    at SyncDelegateHost.read (/app/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:48:21)
    at WebpackCompilerHost.readFileBuffer (/app/node_modules/@ngtools/webpack/src/compiler_host.js:166:44)
    at VirtualFileSystemDecorator.readFile (/app/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:44:54)
    at processResource (/app/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:365:2)

**Comment by sdirix** [comment]
This is a very old issue as we not even support Angular 11 anymore. Closing.
